//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backup.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApertureBackupContext : DbContext
    {
        public ApertureBackupContext()
            : base("name=ApertureBackupContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BackupFile> BackupFiles { get; set; }
        public DbSet<BackupFolder> BackupFolders { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserAccount> UserAccounts { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<UserLog> UserLogs { get; set; }
        public DbSet<BackupFileState> BackupFileStates { get; set; }
    }
}
